language: ruby
rvm:
- 2.3.0
bundler_args: "--without production"
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test
- bundle exec rake db:migrate --trace
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Z4CkzXtpTxOND7VEfpjvKFY9ATALe3HlZGqfNzf4Zr5+Zcq0g8YI7YlTONec39KAsacKVT/elwxXnIbRMjL+Nq0oJz4bEHp8km2TbXC5euom1mnGdhT09oj7eU1M+FqcxPGBz62G0mSjUn8QVsCokGrzeOSLQS1B1Bv2457Lwoc=
  app: twenty2street
  on:
    repo: gabrielc63/22street
